name: ETF Blueprint CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Lint with ruff
      run: |
        pip install ruff
        ruff check .
        
    - name: Check formatting with black
      run: |
        pip install black
        black --check .
        
    - name: Test with pytest
      run: |
        pytest src/backend/tests/ -v
        
    - name: Generate test report
      run: |
        python -m pytest src/backend/tests/ --html=src/backend/tests/report.html --self-contained-html
        
    - name: Archive test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: src/backend/tests/report.html 