[theme]
# Paleta de cores moderna para fintech
primaryColor = "#4F8BF9"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FE"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false 